const js = require('@eslint/js');
const globals = require('globals');

/**
 * Flat config for the Cloud Functions codebase.
 *
 * This file exists because linting here was silently doing nothing. ESLint 8.57
 * switches to flat-config mode as soon as it finds an eslint.config.js anywhere
 * up the directory tree — the repo root has one — and in that mode legacy
 * .eslintrc.js files are ignored entirely, with no warning. `npm run lint` in
 * functions/ therefore resolved to a config with zero rules, and a deliberately
 * broken probe file passed clean. Since firebase.json runs that lint as a
 * predeploy hook, it was gating deploys on nothing.
 *
 * Scope note: the previous .eslintrc.js extended eslint-config-google, which
 * reported 587 errors against this codebase — 386 of them indentation, because
 * the code is written with 4 spaces and google mandates 2. None of them were
 * bugs. Auto-fixing would have reformatted every file for no correctness gain
 * and made real changes hard to review.
 *
 * So this config keeps the rules that catch mistakes and drops the ones that
 * only enforce a house style the codebase never followed. It reports zero errors
 * on the current code, which means it can be enforced immediately rather than
 * being another lint that everyone learns to ignore.
 */
module.exports = [
    {
        // Generated by scripts/prepare-functions.cjs from the app's TypeScript
        // sources; lint the originals, not the bundle.
        ignores: ['shared/**', 'node_modules/**'],
    },
    js.configs.recommended,
    {
        files: ['**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'commonjs',
            globals: {
                ...globals.node,
                // Available on the Node 20 runtime these functions target.
                fetch: 'readonly',
            },
        },
        rules: {
            // Unused function arguments are common and harmless in callback
            // signatures (req, res, next); unused *variables* usually signal a
            // mistake, so those still error.
            'no-unused-vars': ['error', {
                args: 'none',
                ignoreRestSiblings: true,
            }],

            // Beyond eslint:recommended — cheap rules that catch real defects.
            'no-const-assign': 'error',
            'no-var': 'error',
            // destructuring: 'all' so a `let { a, b } = x` where only one member
            // is reassigned isn't flagged — splitting those into separate
            // declarations to satisfy the rule reads worse than the original.
            'prefer-const': ['error', { destructuring: 'all' }],
            eqeqeq: ['error', 'smart'],
            'no-throw-literal': 'error',
            'no-return-await': 'error',
            'require-atomic-updates': 'error',
        },
    },
];
