import { useState, useEffect } from 'react';
import { thumbnailUrl } from '../lib/imageThumbs';

interface OptimizedImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
    src: string;
    alt: string;
    optimizedWidth?: number;
    quality?: number;
    priority?: boolean;
}

function resolveImageSrc(src: string, optimizedWidth: number, quality: number): string {
    if (!src) return '';

    // Images in our own Storage bucket get a resized variant generated by the
    // storage-resize-images extension. Previously these were exempted from any
    // resizing "for maximum speed", which meant a grid cell rendering at ~260px
    // downloaded the full archival scan — up to 33 MB for one thumbnail. If the
    // variant doesn't exist yet (uploaded before the extension, pending the
    // backfill) this URL 404s and onError below falls back to the original.
    const ownStorageThumb = thumbnailUrl(src, optimizedWidth);
    if (ownStorageThumb) return ownStorageThumb;

    // googleusercontent images are already served at sensible sizes and aren't
    // ours to resize.
    const isGoogleHosted = src.includes('firebasestorage.googleapis.com') ||
                           src.includes('storage.googleapis.com') ||
                           src.includes('googleusercontent.com');

    if (src.startsWith('http') && !src.includes('images.weserv.nl') && !isGoogleHosted) {
        return `https://images.weserv.nl/?url=${encodeURIComponent(src)}&w=${optimizedWidth}&q=${quality}&output=webp&fit=cover`;
    }
    return src;
}

export function OptimizedImage({ src, alt, optimizedWidth = 400, quality = 80, priority = false, ...props }: OptimizedImageProps) {
    const [imgSrc, setImgSrc] = useState<string>(() => resolveImageSrc(src, optimizedWidth, quality));
    const [error, setError] = useState(false);

    useEffect(() => {
        if (!src) return;
        setError(false);
        setImgSrc(resolveImageSrc(src, optimizedWidth, quality));
    }, [src, optimizedWidth, quality]);

    if (!src) return null;

    return (
        <img
            src={error ? src : (imgSrc || src)}
            alt={alt}
            onError={() => {
                if (!error) {
                    setError(true);
                }
            }}
            loading={priority ? 'eager' : 'lazy'}
            decoding="async"
            {...(priority ? ({ fetchpriority: 'high' } as any) : {})}
            {...props}
        />
    );
}
